name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Set up Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Set up Git config
      - name: Setup git config
        run: |
          git config user.name "Github Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Install dependencies
      - name: Install dependencies (npm install)
        run: |
          if [ ! -f package-lock.json ]; then
            npm install
          fi
          npm ci

      # Build the project
      - name: Build
        run: npm run build

      # Save version tag
      - name: Save version
        id: version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "TAG=$VERSION" >> $GITHUB_ENV

      # Increase version
      - name: Increase version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "TAG=$VERSION" >> $GITHUB_ENV
          npm version patch --no-git-tag-version

      # Commit and push version changes
      - name: Commit and push version change
        run: |
          git add package.json package-lock.json
          git diff --cached
          git commit -m "Bump version to ${{ env.TAG }}" || echo "No changes to commit"

      # Set up Git authentication for pushing changes
      - name: Set up Git authentication
        run: |
          git config --global user.name "Github Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/haziqothman/mypusara.git

      # Push changes to the repository
      - name: Push changes
        run: |
          git push origin main

      # Login to Docker Hub Registry
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # Check the tag to ensure it's correctly set
      - name: Check tag
        run: echo "Tag is ${{ env.TAG }}"

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build . --file Dockerfile --tag haziqothman:${{ env.TAG }}
          docker images

      # Push the Docker image to Docker Hub
      - name: Push to Docker Hub
        run: |
          docker push haziqothman:${{ env.TAG }}
