name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Setup git config
        run: |
          git config user.name "Github Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies (npm install)
        run: |
          if [ ! -f package-lock.json ]; then
            npm install
          fi
          npm ci

      - name: Build
        run: npm run build

      - name: Save version
        id: version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "TAG=$VERSION" >> $GITHUB_ENV

      - name: Increase version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "TAG=$VERSION" >> $GITHUB_ENV
          npm version patch --no-git-tag-version

      - name: Commit and push version change
        run: |
          git add package.json package-lock.json
          git diff --cached
          git commit -m "Bump version to ${{ env.TAG }}" || echo "No changes to commit"

      # Set up Git authentication with GH_TOKEN
      - name: Set up Git authentication
        run: |
          git config --global user.name "Github Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/haziqothman/mypusara.git

      # Push changes to the repository
      - name: Push changes
        run: |
          git push origin main

      # Docker Hub login (already using your token)
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # Build Docker image
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag haziqothman:${{ env.TAG }}

      # Push to Docker Hub
      - name: Push to Docker Hub
        run: docker push haziqothman:${{ env.TAG }}
